name: Npm run check

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  check:
    uses: soos-io/.github/.github/workflows/npm-check-workflow.yml@main
