name: Run SOOS CSA

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  csa:
    uses: soos-io/.github/.github/workflows/soos-csa-docker-workflow.yml@main
    secrets: inherit
