name: Run SOOS SCA

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  sca:
    uses: soos-io/.github/.github/workflows/soos-sca-workflow.yml@main
    secrets: inherit
