name: Run SOOS SAST via Docker

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  sast:
    uses: soos-io/.github/.github/workflows/soos-sast-docker-workflow.yml@main
    secrets: inherit
