on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        registry-url: "https://registry.npmjs.org"

    - name: Clean Install
      run: npm ci

    - name: Run Check
      run: npm run check --if-present