on:
  workflow_call:
    inputs:
      target_image:
        required: true
        type: string
    secrets:
      SOOS_CLIENT_ID:
        required: true
      SOOS_API_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Run SOOS CSA
      uses: soos-io/soos-csa-github-action@v1
      with:
        project_name: ${{ github.event.repository.name }}
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}
        target_image: ${{ inputs.target_image }}